import streamlit as st
import os
import pandas as pd
from pathlib import Path

# -------------------------------------------------------
# Page Configuration
# -------------------------------------------------------
st.set_page_config(
    page_title="Business Analytics Dashboard",
    page_icon="📊",
    layout="wide"
)

BASE_DIR = Path(__file__).resolve().parent

# -------------------------------------------------------
# Sidebar Navigation
# -------------------------------------------------------
st.sidebar.title("📂 Navigation")

page = st.sidebar.radio(
    "Go to",
    [
        "Overview",
        "Trends",
        "Data Explorer"
    ]
)

# =======================================================
# OVERVIEW PAGE
# =======================================================
if page == "Overview":

    st.title("📊 Business Analytics Dashboard")

    st.header("Key Performance Indicators")

    # KPI Cards
    col1, col2, col3, col4, col5 = st.columns(5)

    with col1:
        st.metric(
            "Revenue",
            "$11.73M",
            "+12.5%"
        )

    with col2:
        st.metric(
            "Top Product",
            "Alpha",
            "Highest Sales"
        )

    with col3:
        st.metric(
            "Avg Order Value",
            "$92",
            "+2.1%"
        )

    with col4:
        st.metric(
            "Best Quarter",
            "Q4",
            "+15%"
        )

    with col5:
        st.metric(
            "Marketing ROI",
            "0.93",
            "Strong Correlation"
        )

    st.divider()

    st.header("Business Summary")

    st.subheader("Revenue by Product Line")

    chart_path = BASE_DIR / "output" / "chart1_revenue_by_product.png"

    if chart_path.exists():
        st.image(str(chart_path), use_container_width=True)
    else:
        st.info("Revenue by Product chart will appear here.")

    with st.expander("About These Metrics"):

        st.write("""
        - Revenue represents total sales generated by each product line.
        - Alpha is currently the highest-performing product.
        - Average Order Value (AOV) represents the average spending per order.
        - Q4 recorded the strongest quarterly revenue.
        - Marketing ROI indicates a strong relationship between marketing spend and revenue.
        """)

# =======================================================
# TRENDS PAGE
# =======================================================
elif page == "Trends":

    st.title("📈 Trend Analysis")

    st.header("Monthly Revenue Trend")

    st.subheader("Revenue Growth Over Time")

    chart_path = BASE_DIR / "output" / "chart2_revenue_trend.png"

    if chart_path.exists():
        st.image(str(chart_path), use_container_width=True)
    else:
        st.info("Revenue Trend chart will appear here.")

    st.divider()

    st.header("Quarterly Revenue Composition")

    st.subheader("Revenue Contribution by Quarter")

    chart_path = BASE_DIR / "output" / "chart4_revenue_composition.png"

    if chart_path.exists():
        st.image(str(chart_path), use_container_width=True)
    else:
        st.info("Quarterly Revenue chart will appear here.")

    with st.expander("Business Insights"):

        st.write("""
        • Revenue steadily increased throughout the year.

        • November recorded the highest monthly revenue.

        • Q4 generated the largest share of total revenue.

        • Seasonal demand contributed significantly to business growth.
        """)

# =======================================================
# DATA EXPLORER PAGE
# =======================================================
elif page == "Data Explorer":

    st.title("📂 Data Explorer")

    st.header("Business Data")

    col1, col2 = st.columns(2)

    with col1:

        st.subheader("Order Value Distribution")

        chart_path = BASE_DIR / "output" / "chart3_order_value_distribution.png"

        if chart_path.exists():
            st.image(str(chart_path), use_container_width=True)
        else:
            st.info("Order Value Distribution chart will appear here.")

    with col2:

        st.subheader("Marketing Spend vs Revenue")

        chart_path = BASE_DIR / "output" / "chart5_marketing_vs_revenue.png"

        if chart_path.exists():
            st.image(str(chart_path), use_container_width=True)
        else:
            st.info("Marketing vs Revenue chart will appear here.")

    st.divider()

    st.header("Dataset Information")

    with st.expander("View Dataset Information"):

        st.write("""
        This dashboard is based on business analytics data that includes:

        - Product Line Revenue
        - Monthly Revenue Trends
        - Quarterly Revenue Composition
        - Customer Order Values
        - Marketing Spend
        - Revenue Correlation

        Future versions of this dashboard will include filtering,
        data tables, CSV export, and interactive analytics.
        """)

    with st.expander("Methodology"):

        st.write("""
        Revenue is calculated as the total sales generated by each
        product line. Quarterly and monthly trends are derived from
        aggregated transaction data.

        Marketing effectiveness is evaluated using correlation between
        monthly marketing spend and generated revenue.
        """)

st.divider()

# ---------------------------
# Dataset Upload
# ---------------------------

st.header("Dataset Upload")

uploaded_file = st.file_uploader(
    "Upload CSV or JSON",
    type=["csv", "json"]
)

if uploaded_file is None:
    st.info("Upload a CSV or JSON file to view the dataset preview.")
    st.stop()

try:
    if uploaded_file.name.endswith(".csv"):
        df = pd.read_csv(uploaded_file)
    elif uploaded_file.name.endswith(".json"):
        df = pd.read_json(uploaded_file)
    else:
        st.error("Unsupported file type.")
        st.stop()

    if df.empty:
        st.warning("Uploaded file is empty.")
        st.stop()

except Exception:
    st.error("Could not read this file. Please check the format and try again.")
    st.stop()

st.divider()

# ---------------------------
# Session State Workflow
# ---------------------------

# "selected_segment" - stores the confirmed segment or category choice from Step 1.
if "selected_segment" not in st.session_state:
    st.session_state["selected_segment"] = "All"

# "workflow_step" - tracks whether the user has confirmed Step 1 before showing Step 2.
if "workflow_step" not in st.session_state:
    st.session_state["workflow_step"] = 1

# "analysis_result" - caches the Step 2 result so reruns do not recompute it unnecessarily.
if "analysis_result" not in st.session_state:
    st.session_state["analysis_result"] = None

# "filter_date_start" - stores the start date used by the upload analysis filter.
if "filter_date_start" not in st.session_state:
    st.session_state["filter_date_start"] = None

# "filter_date_end" - stores the end date used by the upload analysis filter.
if "filter_date_end" not in st.session_state:
    st.session_state["filter_date_end"] = None

if st.sidebar.button("Reset Workflow"):
    for key in [
        "selected_segment",
        "workflow_step",
        "analysis_result",
        "filter_date_start",
        "filter_date_end",
        "pending_segment_choice",
        "pending_date_start",
        "pending_date_end",
    ]:
        if key in st.session_state:
            del st.session_state[key]
    st.rerun()

st.header("Multi-Step Analysis Workflow")

segment_source_column = None
segment_columns = [column for column in df.columns if df[column].dtype == "object" or str(df[column].dtype).startswith("category")]
if "segment" in df.columns:
    segment_source_column = "segment"
elif segment_columns:
    segment_source_column = segment_columns[0]

if segment_source_column is not None:
    segment_options = ["All"] + sorted(df[segment_source_column].dropna().astype(str).unique().tolist())

    # "pending_segment_choice" - holds the in-progress Step 1 selection before confirmation.
    if "pending_segment_choice" not in st.session_state:
        st.session_state["pending_segment_choice"] = st.session_state["selected_segment"]

    # "pending_date_start" - holds the in-progress start date selection before confirmation.
    if "pending_date_start" not in st.session_state:
        st.session_state["pending_date_start"] = None

    # "pending_date_end" - holds the in-progress end date selection before confirmation.
    if "pending_date_end" not in st.session_state:
        st.session_state["pending_date_end"] = None

    st.subheader("Step 1: Select a Segment")
    segment_choice = st.selectbox(
        f"Choose {segment_source_column.title()}",
        options=segment_options,
        index=segment_options.index(st.session_state["pending_segment_choice"])
        if st.session_state["pending_segment_choice"] in segment_options else 0,
        key="pending_segment_choice",
    )

    if st.button("Confirm Selection"):
        st.session_state["selected_segment"] = segment_choice
        st.session_state["workflow_step"] = 2

        filtered_df = df.copy()
        if segment_choice != "All":
            filtered_df = filtered_df[filtered_df[segment_source_column].astype(str) == segment_choice]

        st.session_state["analysis_result"] = {
            "segment_column": segment_source_column,
            "segment_value": segment_choice,
            "rows": int(len(filtered_df)),
            "columns": int(len(filtered_df.columns)),
            "null_pct": float((filtered_df.isnull().sum().sum() / max(filtered_df.shape[0] * filtered_df.shape[1], 1)) * 100),
        }

        st.session_state["filter_date_start"] = None
        st.session_state["filter_date_end"] = None

    if st.session_state["workflow_step"] >= 2:
        st.subheader("Step 2: Analysis")
        chosen_segment = st.session_state["selected_segment"]
        st.write(f"Analysing: {chosen_segment}")

        if st.session_state["analysis_result"] is None or st.session_state["analysis_result"].get("segment_value") != chosen_segment:
            recalculated_df = df.copy()
            if chosen_segment != "All":
                recalculated_df = recalculated_df[recalculated_df[segment_source_column].astype(str) == chosen_segment]

            st.session_state["analysis_result"] = {
                "segment_column": segment_source_column,
                "segment_value": chosen_segment,
                "rows": int(len(recalculated_df)),
                "columns": int(len(recalculated_df.columns)),
                "null_pct": float((recalculated_df.isnull().sum().sum() / max(recalculated_df.shape[0] * recalculated_df.shape[1], 1)) * 100),
            }

        analysis_result = st.session_state["analysis_result"]
        workflow_col1, workflow_col2, workflow_col3 = st.columns(3)

        with workflow_col1:
            st.metric("Rows", f"{analysis_result['rows']:,}")

        with workflow_col2:
            st.metric("Columns", f"{analysis_result['columns']:,}")

        with workflow_col3:
            st.metric("Null %", f"{analysis_result['null_pct']:.1f}%")

        st.caption("The confirmed choice stays available when other widgets rerun the page.")
else:
    st.info("No categorical column was found for the step-by-step workflow.")

# ---------------------------
# Dataset Summary
# ---------------------------

st.header("Dataset Preview")

col1, col2, col3 = st.columns(3)

with col1:
    st.metric("Rows", len(df))

with col2:
    st.metric("Columns", len(df.columns))

with col3:
    total_nulls = df.isnull().sum().sum()
    total_cells = max(df.shape[0] * df.shape[1], 1)
    null_pct = (total_nulls / total_cells) * 100
    st.metric("Null %", f"{null_pct:.1f}%")

st.divider()

# ---------------------------
# First 10 Rows
# ---------------------------

st.subheader("First 10 Rows")
st.dataframe(df.head(10), use_container_width=True)

# ---------------------------
# Column Summary
# ---------------------------

st.subheader("Column Summary")

summary = pd.DataFrame({
    "Column": df.columns,
    "Type": df.dtypes.astype(str).values,
    "Non-Null": df.notnull().sum().values,
    "Null Count": df.isnull().sum().values,
    "Null %": (df.isnull().sum() / len(df) * 100).round(1).values
})

st.dataframe(summary, use_container_width=True)

# ---------------------------
# Descriptive Statistics
# ---------------------------

st.subheader("Descriptive Statistics")

st.dataframe(
    df.describe(include="all"),
    use_container_width=True
)

# ---------------------------
# Quick Filter
# ---------------------------

st.subheader("Quick Filter")

filter_columns = df.columns.tolist()

selected_column = st.selectbox(
    "Select a column",
    filter_columns
)

unique_values = df[selected_column].dropna().unique()

if len(unique_values) > 0:
    selected_value = st.selectbox(
        "Select a value",
        unique_values
    )

    filtered_df = df[df[selected_column] == selected_value]

    st.write(f"Filtered Records: {len(filtered_df)}")

    st.dataframe(
        filtered_df,
        use_container_width=True
    )

st.divider()

# ---------------------------
# Quick Exploration
# ---------------------------

st.subheader("Quick Exploration")

numeric_cols = df.select_dtypes(include="number").columns.tolist()

if numeric_cols:

    selected_numeric = st.selectbox(
        "Choose Numeric Column",
        numeric_cols
    )

    st.bar_chart(
        df[selected_numeric].value_counts().head(20)
    )

else:
    st.info("No numeric columns available.")

# ---------------------------
# Download Dataset
# ---------------------------

st.subheader("Export Dataset")

csv = df.to_csv(index=False)

st.download_button(
    label="Download CSV",
    data=csv,
    file_name="uploaded_dataset.csv",
    mime="text/csv"
)
