import streamlit as st
 feature/streamlit-dashboard-shell
import os

# -------------------------------------------------------
# Page Configuration
# -------------------------------------------------------
st.set_page_config(
    page_title="Business Analytics Dashboard",
    page_icon="📊",
    layout="wide"
)

# -------------------------------------------------------
# Sidebar Navigation
# -------------------------------------------------------
st.sidebar.title("📂 Navigation")

page = st.sidebar.radio(
    "Go to",
    [
        "Overview",
        "Trends",
        "Data Explorer"
    ]
)

# =======================================================
# OVERVIEW PAGE
# =======================================================
if page == "Overview":

    st.title("📊 Business Analytics Dashboard")

    st.header("Key Performance Indicators")

    # KPI Cards
    col1, col2, col3, col4, col5 = st.columns(5)

    with col1:
        st.metric(
            "Revenue",
            "$11.73M",
            "+12.5%"
        )

    with col2:
        st.metric(
            "Top Product",
            "Alpha",
            "Highest Sales"
        )

    with col3:
        st.metric(
            "Avg Order Value",
            "$92",
            "+2.1%"
        )

    with col4:
        st.metric(
            "Best Quarter",
            "Q4",
            "+15%"
        )

    with col5:
        st.metric(
            "Marketing ROI",
            "0.93",
            "Strong Correlation"
        )

    st.divider()

    st.header("Business Summary")

    st.subheader("Revenue by Product Line")

    chart_path = "output/chart1_revenue_by_product.png"

    if os.path.exists(chart_path):
        st.image(chart_path, use_container_width=True)
    else:
        st.info("Revenue by Product chart will appear here.")

    with st.expander("About These Metrics"):

        st.write("""
        - Revenue represents total sales generated by each product line.
        - Alpha is currently the highest-performing product.
        - Average Order Value (AOV) represents the average spending per order.
        - Q4 recorded the strongest quarterly revenue.
        - Marketing ROI indicates a strong relationship between marketing spend and revenue.
        """)

# =======================================================
# TRENDS PAGE
# =======================================================
elif page == "Trends":

    st.title("📈 Trend Analysis")

    st.header("Monthly Revenue Trend")

    st.subheader("Revenue Growth Over Time")

    chart_path = "output/chart2_revenue_trend.png"

    if os.path.exists(chart_path):
        st.image(chart_path, use_container_width=True)
    else:
        st.info("Revenue Trend chart will appear here.")

    st.divider()

    st.header("Quarterly Revenue Composition")

    st.subheader("Revenue Contribution by Quarter")

    chart_path = "output/chart4_revenue_composition.png"

    if os.path.exists(chart_path):
        st.image(chart_path, use_container_width=True)
    else:
        st.info("Quarterly Revenue chart will appear here.")

    with st.expander("Business Insights"):

        st.write("""
        • Revenue steadily increased throughout the year.

        • November recorded the highest monthly revenue.

        • Q4 generated the largest share of total revenue.

        • Seasonal demand contributed significantly to business growth.
        """)

# =======================================================
# DATA EXPLORER PAGE
# =======================================================
elif page == "Data Explorer":

    st.title("📂 Data Explorer")

    st.header("Business Data")

    col1, col2 = st.columns(2)

    with col1:

        st.subheader("Order Value Distribution")

        chart_path = "output/chart3_order_value_distribution.png"

        if os.path.exists(chart_path):
            st.image(chart_path, use_container_width=True)
        else:
            st.info("Order Value Distribution chart will appear here.")

    with col2:

        st.subheader("Marketing Spend vs Revenue")

        chart_path = "output/chart5_marketing_vs_revenue.png"

        if os.path.exists(chart_path):
            st.image(chart_path, use_container_width=True)
        else:
            st.info("Marketing vs Revenue chart will appear here.")

    st.divider()

    st.header("Dataset Information")

    with st.expander("View Dataset Information"):

        st.write("""
        This dashboard is based on business analytics data that includes:

        - Product Line Revenue
        - Monthly Revenue Trends
        - Quarterly Revenue Composition
        - Customer Order Values
        - Marketing Spend
        - Revenue Correlation

        Future versions of this dashboard will include filtering,
        data tables, CSV export, and interactive analytics.
        """)

    with st.expander("Methodology"):

        st.write("""
        Revenue is calculated as the total sales generated by each
        product line. Quarterly and monthly trends are derived from
        aggregated transaction data.

        Marketing effectiveness is evaluated using correlation between
        monthly marketing spend and generated revenue.
        """)
=======
import pandas as pd

st.set_page_config(
    page_title="Dataset Upload",
    page_icon="📂",
    layout="wide"
)

st.title("📂 Dataset Upload & Dynamic Preview")
st.write("Upload a CSV or JSON dataset to preview, validate, and explore your data.")

uploaded_file = st.file_uploader(
    "Upload CSV or JSON",
    type=["csv", "json"]
)

if uploaded_file is None:
    st.info("Upload a CSV or JSON file to begin.")
    st.stop()

try:
    # Load file
    if uploaded_file.name.endswith(".csv"):
        df = pd.read_csv(uploaded_file)

    elif uploaded_file.name.endswith(".json"):
        df = pd.read_json(uploaded_file)

    else:
        st.error("Unsupported file type.")
        st.stop()

    # Empty file validation
    if df.empty:
        st.warning("Uploaded file is empty.")
        st.stop()

except Exception:
    st.error("Could not read this file. Please check the format and try again.")
    st.stop()

# Success Message
st.success(
    f"Loaded **{uploaded_file.name}** ({len(df)} rows, {len(df.columns)} columns)"
)

st.divider()

# ---------------------------
# Dataset Summary
# ---------------------------

st.header("Dataset Preview")

col1, col2, col3 = st.columns(3)

with col1:
    st.metric("Rows", len(df))

with col2:
    st.metric("Columns", len(df.columns))

with col3:
    total_nulls = df.isnull().sum().sum()
    total_cells = max(df.shape[0] * df.shape[1], 1)
    null_pct = (total_nulls / total_cells) * 100
    st.metric("Null %", f"{null_pct:.1f}%")

st.divider()

# ---------------------------
# First 10 Rows
# ---------------------------

st.subheader("First 10 Rows")
st.dataframe(df.head(10), use_container_width=True)

# ---------------------------
# Column Summary
# ---------------------------

st.subheader("Column Summary")

summary = pd.DataFrame({
    "Column": df.columns,
    "Type": df.dtypes.astype(str).values,
    "Non-Null": df.notnull().sum().values,
    "Null Count": df.isnull().sum().values,
    "Null %": (df.isnull().sum() / len(df) * 100).round(1).values
})

st.dataframe(summary, use_container_width=True)

# ---------------------------
# Descriptive Statistics
# ---------------------------

st.subheader("Descriptive Statistics")

st.dataframe(
    df.describe(include="all"),
    use_container_width=True
)

# ---------------------------
# Quick Filter
# ---------------------------

st.subheader("Quick Filter")

filter_columns = df.columns.tolist()

selected_column = st.selectbox(
    "Select a column",
    filter_columns
)

unique_values = df[selected_column].dropna().unique()

if len(unique_values) > 0:
    selected_value = st.selectbox(
        "Select a value",
        unique_values
    )

    filtered_df = df[df[selected_column] == selected_value]

    st.write(f"Filtered Records: {len(filtered_df)}")

    st.dataframe(
        filtered_df,
        use_container_width=True
    )

st.divider()

# ---------------------------
# Quick Exploration
# ---------------------------

st.subheader("Quick Exploration")

numeric_cols = df.select_dtypes(include="number").columns.tolist()

if numeric_cols:

    selected_numeric = st.selectbox(
        "Choose Numeric Column",
        numeric_cols
    )

    st.bar_chart(
        df[selected_numeric].value_counts().head(20)
    )

else:
    st.info("No numeric columns available.")

# ---------------------------
# Download Dataset
# ---------------------------

st.subheader("Export Dataset")

csv = df.to_csv(index=False)

st.download_button(
    label="Download CSV",
    data=csv,
    file_name="uploaded_dataset.csv",
    mime="text/csv"
)
 main
