import streamlit as st
import os

# -------------------------------------------------------
# Page Configuration
# -------------------------------------------------------
st.set_page_config(
    page_title="Business Analytics Dashboard",
    page_icon="📊",
    layout="wide"
)

# -------------------------------------------------------
# Sidebar Navigation
# -------------------------------------------------------
st.sidebar.title("📂 Navigation")

page = st.sidebar.radio(
    "Go to",
    [
        "Overview",
        "Trends",
        "Data Explorer"
    ]
)

# =======================================================
# OVERVIEW PAGE
# =======================================================
if page == "Overview":

    st.title("📊 Business Analytics Dashboard")

    st.header("Key Performance Indicators")

    # KPI Cards
    col1, col2, col3, col4, col5 = st.columns(5)

    with col1:
        st.metric(
            "Revenue",
            "$11.73M",
            "+12.5%"
        )

    with col2:
        st.metric(
            "Top Product",
            "Alpha",
            "Highest Sales"
        )

    with col3:
        st.metric(
            "Avg Order Value",
            "$92",
            "+2.1%"
        )

    with col4:
        st.metric(
            "Best Quarter",
            "Q4",
            "+15%"
        )

    with col5:
        st.metric(
            "Marketing ROI",
            "0.93",
            "Strong Correlation"
        )

    st.divider()

    st.header("Business Summary")

    st.subheader("Revenue by Product Line")

    chart_path = "output/chart1_revenue_by_product.png"

    if os.path.exists(chart_path):
        st.image(chart_path, use_container_width=True)
    else:
        st.info("Revenue by Product chart will appear here.")

    with st.expander("About These Metrics"):

        st.write("""
        - Revenue represents total sales generated by each product line.
        - Alpha is currently the highest-performing product.
        - Average Order Value (AOV) represents the average spending per order.
        - Q4 recorded the strongest quarterly revenue.
        - Marketing ROI indicates a strong relationship between marketing spend and revenue.
        """)

# =======================================================
# TRENDS PAGE
# =======================================================
elif page == "Trends":

    st.title("📈 Trend Analysis")

    st.header("Monthly Revenue Trend")

    st.subheader("Revenue Growth Over Time")

    chart_path = "output/chart2_revenue_trend.png"

    if os.path.exists(chart_path):
        st.image(chart_path, use_container_width=True)
    else:
        st.info("Revenue Trend chart will appear here.")

    st.divider()

    st.header("Quarterly Revenue Composition")

    st.subheader("Revenue Contribution by Quarter")

    chart_path = "output/chart4_revenue_composition.png"

    if os.path.exists(chart_path):
        st.image(chart_path, use_container_width=True)
    else:
        st.info("Quarterly Revenue chart will appear here.")

    with st.expander("Business Insights"):

        st.write("""
        • Revenue steadily increased throughout the year.

        • November recorded the highest monthly revenue.

        • Q4 generated the largest share of total revenue.

        • Seasonal demand contributed significantly to business growth.
        """)

# =======================================================
# DATA EXPLORER PAGE
# =======================================================
elif page == "Data Explorer":

    st.title("📂 Data Explorer")

    st.header("Business Data")

    col1, col2 = st.columns(2)

    with col1:

        st.subheader("Order Value Distribution")

        chart_path = "output/chart3_order_value_distribution.png"

        if os.path.exists(chart_path):
            st.image(chart_path, use_container_width=True)
        else:
            st.info("Order Value Distribution chart will appear here.")

    with col2:

        st.subheader("Marketing Spend vs Revenue")

        chart_path = "output/chart5_marketing_vs_revenue.png"

        if os.path.exists(chart_path):
            st.image(chart_path, use_container_width=True)
        else:
            st.info("Marketing vs Revenue chart will appear here.")

    st.divider()

    st.header("Dataset Information")

    with st.expander("View Dataset Information"):

        st.write("""
        This dashboard is based on business analytics data that includes:

        - Product Line Revenue
        - Monthly Revenue Trends
        - Quarterly Revenue Composition
        - Customer Order Values
        - Marketing Spend
        - Revenue Correlation

        Future versions of this dashboard will include filtering,
        data tables, CSV export, and interactive analytics.
        """)

    with st.expander("Methodology"):

        st.write("""
        Revenue is calculated as the total sales generated by each
        product line. Quarterly and monthly trends are derived from
        aggregated transaction data.

        Marketing effectiveness is evaluated using correlation between
        monthly marketing spend and generated revenue.
        """)